name: Sync Sources

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *" 

jobs:
  Sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Prepare Dependences
        run: pip install requests

      - name: Run sync
        env:
          SRC_UA:       ${{ secrets.SRC_UA }}
          SRC_LOC:    ${{ secrets.SRC_LOC }}
          AUX_ENDPOINT: ${{ secrets.AUX_ENDPOINT }}
          AUX_KEY:      ${{ secrets.AUX_KEY }}
        run: python sync/sync.py

      - name: List results
        run: ls -lh ./sources/ 2>/dev/null || echo "(no files)"

      - name: Extract URLs
        run: |
          scripts=(
            "channel_free.py"
            "channel_pay.py" 
            "channel_foreign.py"
            "channel_province.py"
            "channel_province_ground.py"
            "channel_hk.py"
            "channel_mo.py"
            "channel_tw.py"
          )
    
          for script in "${scripts[@]}"; do
            echo "Running $script..."
            python "process/$script"
          done

      - name: List results(extracted)
        run: ls -lh ./sources/temp 2>/dev/null || echo "(no files)"

      - name: Assembly files
        run: python assembly/assembly.py

      - name: Release files
        env:
          REMOTE_HOST:        ${{ secrets.REMOTE_HOST }}
          STORAGE_ACCOUNT_ID: ${{ secrets.STORAGE_ACCOUNT_ID }}
          STORAGE_NS_ID:      ${{ secrets.STORAGE_NS_ID }}
          STORAGE_API_TOKEN:  ${{ secrets.STORAGE_API_TOKEN }}
          STORAGE_KEY_NAME:   ${{ secrets.STORAGE_KEY_NAME }}
        run: python output/output.py

      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Clean up old workflow records
        run: python .github/scripts/clean.py
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          WORKFLOW_NAME: "Sync Sources"
          KEEP_COUNT: 2
